export {
    mdiCompassOffOutline,
    mdiCompassOutline,
    mdiCompass,
    mdiStorePlus,
    mdiMagnify,
    mdiClose,
    mdiBlockHelper,
    mdiPencilOutline,
    mdiHome,
    mdiHomeOutline,
    mdiCogOutline,
    mdiBadgeAccountHorizontalOutline,
    mdiPaletteOutline,
    mdiInboxOutline,
    mdiChevronLeft,
    mdiDomain,
    mdiCircleMedium,
    mdiChevronDown,
    mdiAccountCircleOutline,
    mdiPlus
} from "@mdi/js"   